- name: Setup gee4 bath sensor server
  hosts: all
  become: true
  vars_files:
    - vars/prod.yaml
  tasks:
  - name: Set hostname
    hostname:
      name: "{{ hostname }}"
  - name: Set hosts
    template:
      src: hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644
      backup: yes
  - name: Create locale japanese
    locale_gen:
      name: "{{ locale }}"
  - name: Update locale
    command: update-locale "{{ locale }}"
  - name: Set timezone
    timezone:
      name: "{{ timezone }}"
  - name: Enable avahi
    systemd:
      name: avahi-daemon
      enabled: yes
  - name: Set rc.local file
    copy:
      src: rc.local
      dest: /etc/rc.local
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx
      backup: yes
  #
  # gee4-bath-server
  #
  - name: Install ruby
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - ruby2.3
      - ruby2.3-dev
  - name: Clone gee4-bath-server repo
    git:
      repo: 'https://github.com/geekh0use/gee4-bath-sensor'
      dest: /opt/gee4-bath-sensor
  - name: Set systemd service file for gee4-bath-sensor
    copy:
      src: etc/systemd/system/furo.service
      dest: /etc/systemd/system/furo.service
      owner: root
      group: root
      mode: '664'
  - name: Start furo.service
    systemd:
      state: started
      enabled: yes
      name: furo.service
      daemon_reload: yes
